import sc from 'subcollider'

const scales = {
	major: new sc.Scale.major(),
	minor: new sc.Scale.major(),
	whole: new sc.Scale.whole(),
	
	augmented: new sc.Scale.augmented(),
	augmented2: new sc.Scale.augmented2(),
	ionian: new sc.Scale.ionian(),
	dorian: new sc.Scale.dorian(),
	phrygian: new sc.Scale.phrygian(),
	lydian: new sc.Scale.lydian(),
	mixolydian: new sc.Scale.mixolydian(),
	aeolian: new sc.Scale.aeolian(),
	locrian: new sc.Scale.locrian(),
	harmonicMinor: new sc.Scale.harmonicMinor(),
	harmonicMajor: new sc.Scale.harmonicMajor(),
	melodicMinor: new sc.Scale.melodicMinor(),
	melodicMinorDesc: new sc.Scale.melodicMinorDesc(),
	melodicMajor: new sc.Scale.melodicMajor(),
	minorPentatonic: new sc.Scale.minorPentatonic(),
	majorPentatonic: new sc.Scale.majorPentatonic(),
	
	hexMajor7: new sc.Scale.hexMajor7(),
	hexDorian: new sc.Scale.hexDorian(),
	hexPhrygian: new sc.Scale.hexPhrygian(),
	hexSus: new sc.Scale.hexSus(),
	hexMajor6: new sc.Scale.hexMajor6(),
	hexAeolian: new sc.Scale.hexAeolian(),

	ritusen: new sc.Scale.ritusen(),
	egyptian: new sc.Scale.egyptian(),
	hirajoshi: new sc.Scale.hirajoshi(),
	kumoi: new sc.Scale.kumoi(),
	iwato: new sc.Scale.iwato(),
	ryukyu: new sc.Scale.ryukyu(),
	chinese: new sc.Scale.chinese(),
	indian: new sc.Scale.indian(),
	pelog: new sc.Scale.pelog(),
	prometheus: new sc.Scale.prometheus(),
	scriabin: new sc.Scale.scriabin(),
	gong: new sc.Scale.gong(),
	shang: new sc.Scale.shang(),
	jiao: new sc.Scale.jiao(),
	zhi: new sc.Scale.zhi(),
	yu: new sc.Scale.yu(),
}
export default scales;