export const UPDATE_OCTAVE = 'UPDATE_OCTAVE'
export const UPDATE_SCALE = 'UPDATE_SCALE'
export const UPDATE_MODE = 'UPDATE_MODE'
export const UPDATE_METER_BEATS = 'UPDATE_METER_BEATS'
export const UPDATE_METER_TIME = 'UPDATE_METER_TIME'

export const UPDATE_ENVELOPE = 'UPDATE_ENVELOPE'

export const UPDATE_WAVEFORM = 'UPDATE_WAVEFORM'

export const UPDATE_BPM = 'UPDATE_BPM'
export const TRANSPORT_START = 'TRANSPORT_START'
export const TRANSPORT_STOP = 'TRANSPORT_STOP'
export const TRANSPORT_TOGGLE = 'TRANSPORT_TOGGLE'

export const TOOL_CHANGE = 'TOOL_CHANGE'
export const VIEW_CHANGE = 'VIEW_CHANGE'
export const TOOL_SETTING_CHANGE = 'TOOL_SETTING_CHANGE'
export const TOOL_SETTINGS_CHANGE = 'TOOL_SETTINGS_CHANGE'

export const ADD_RING_NODE = 'ADD_RING_NODE'
export const REMOVE_RING_NODE = 'REMOVE_RING_NODE'
export const ADD_RADAR_NODE = 'ADD_RADAR_NODE'
export const REMOVE_RADAR_NODE = 'REMOVE_RADAR_NODE'
export const ADD_POINT_NODE = 'ADD_POINT_NODE'
export const REMOVE_POINT_NODE = 'REMOVE_POINT_NODE'
export const ADD_ARC_NODE = 'ADD_ARC_NODE'
export const REMOVE_ARC_NODE = 'REMOVE_ARC_NODE'