export default [
	{ value: '1n', 		label: '1 •', 		icon: '1n', 	text: 'Dotted whole note' },
	{ value: '1n', 		label: '1', 		icon: '1n', 	text: 'Whole note' },
	{ value: '1t', 		label: '1t', 		icon: '1n', 	text: 'Whole note triplet' },
	{ value: '2n', 		label: '1/2 •', 	icon: '2n', 	text: 'Dotted half note' },
	{ value: '2n', 		label: '1/2', 		icon: '2n', 	text: 'Half note' },
	{ value: '2t', 		label: '1/2t', 		icon: '2n', 	text: 'Half note triplet' },
	{ value: '4n', 		label: '1/4 •', 	icon: '4n', 	text: 'Dotted quarter note' },
	{ value: '4n', 		label: '1/4', 		icon: '4n', 	text: 'Quarter note' },
	{ value: '4t', 		label: '1/4t', 		icon: '4n', 	text: 'Quarter note triplet' },
	{ value: '8n', 		label: '1/8 •', 	icon: '8n', 	text: 'Dotted eighth note' },
	{ value: '8n', 		label: '1/8', 		icon: '8n', 	text: 'Eighth note' },
	{ value: '8t', 		label: '1/8t', 		icon: '8n', 	text: 'Eighth note triplet' },
	{ value: '16n', 	label: '1/16 •', 	icon: '16n', 	text: 'Dotted sixteenth note' },
	{ value: '16n', 	label: '1/16', 		icon: '16n', 	text: 'Sixteenth note' },
	{ value: '16t', 	label: '1/16t', 	icon: '16n', 	text: 'Sixteenth note triplet' },
	{ value: '32n', 	label: '1/32 •', 	icon: '32n', 	text: 'Dotted thirty-second note' },
	{ value: '32n', 	label: '1/32', 		icon: '32n', 	text: 'Thirty-second note' },
	{ value: '32t', 	label: '1/32t', 	icon: '32n', 	text: 'Thirty-second-note triplet' },
	{ value: '64n', 	label: '1/64 •', 	icon: '64n', 	text: 'Dotted sixty-fourth note' },
	{ value: '64n', 	label: '1/64', 		icon: '64n', 	text: 'Sixty-fourth note' },
	{ value: '128n', 	label: '1/128', 	icon: '128n', 	text: 'One-hundred-twenty-eighth note' },
]